apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-app
  namespace: demo-app
spec:
  selector:
    matchLabels:
      app: demo-app
  serviceName: demo-app
  replicas: 3
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: meik99/cloud-computing:dev
        ports:
        - containerPort: 80
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  selector:
    app: demo-app
  ports:
  - port: 80
  type: NodePort