platform: linux
image_resource: 
  type: registry-image
  source: 
    repository: node
    tag: latest


inputs:
  - name: repository
  - name: trigger

outputs:
  - name: trigger

run:
  path: repository/pipeline/tasks/test-demo-app/task.sh
