resources:
  - icon: github
    name: repository
    source:
      uri: https://github.com/meik99/cloud-computing.git
      branch: test-pipeline
    type: git

jobs:
  - name: test-demo-app
    plan:
      - get: repository
        trigger: true
      - task: test
        file: repository/pipeline/tasks/test-demo-app/task.yaml
