resource_types:
  - name: webhook-notification
    type: registry-image
    source:
      repository: flavorjones/webhook-notification-resource
      tag: latest

resources:
  - icon: github
    name: repository
    source:
      uri: https://github.com/meik99/cloud-computing.git
      branch: main
    type: git

  - name: demo-app
    type: registry-image
    icon: docker
    source:
      repository: meik99/cloud-computing
      username: ((dockerhub.username))
      password: ((dockerhub.token))
      tag: dev

  - name: discord
    type: webhook-notification
    icon: bell
    source:
      adapter: DiscordAdapter
      url: ((discord.webhook))

jobs:
  - name: test-demo-app
    plan:
      - get: repository
        trigger: true
      - task: test
        file: repository/pipeline/tasks/test-demo-app/task.yaml      
    on_failure:
      put: discord
      params:
        status: "failed"

  - name: build-and-push
    plan:
      - get: repository
        passed: 
          - test-demo-app
        trigger: true
      - task: build
        privileged: true
        file: repository/pipeline/tasks/build-and-push/task.yaml
      - put: demo-app
        params:
          image: image/image.tar
    on_success:
      put: discord
      params:
        status: "succeeded"
    on_failure:
      put: discord
      params:
        status: "failed"
        