resources:
  - icon: github
    name: repository
    source:
      uri: https://github.com/meik99/cloud-computing.git
      branch: main
    type: git

  - name: demo-app
    type: registry-image
    icon: docker
    source:
      repository: meik99/cloud-computing
      username: ((dockerhub.username))
      password: ((dockerhub.token))
      tag: dev

jobs:
  - name: test-demo-app
    plan:
      - get: repository
        trigger: true
      - task: test
        file: repository/pipeline/tasks/test-demo-app/task.yaml      

  - name: build-and-push
    plan:
      - get: repository
        passed: 
          - test-demo-app
        trigger: true
      - task: build
        privileged: true
        file: repository/pipeline/tasks/build-and-push/task.yaml
      - put: demo-app
        params:
          image: image/image.tar

  - name: demo-echo
    plan:
      - get: repository
        passed: 
          - build-and-push
        trigger: true
      - task: echo-success
        config:
          platform: linux
          image_resource: 
            type: registry-image
            source: 
              repository: alpine
              tag: latest
          run: 
            path: echo 
            args: 
              - Successfully built
