resources:
  - icon: github
    name: repository
    source:
      uri: https://github.com/meik99/cloud-computing.git
      branch: main
    type: git

  - name: demo-app
    type: registry-image
    icon: docker
    source:
      repository: meik99/cloud-computing
      username: ((dockerhub.username))
      password: ((dockerhub.token))
      tag: dev

  - name: trigger
    type: mock    

jobs:
  - name: test-demo-app
    plan:
      - get: repository
        trigger: true
      - task: test
        file: repository/pipeline/tasks/test-demo-app/task.yaml
      - put: trigger
        params:
          version: mock

  - name: build-and-push
    plan:
      - get: trigger
        passed: 
          - test-demo-app
        trigger: true
      - get: repository
      - task: build
        privileged: true
        file: repository/pipeline/tasks/build-and-push/task.yaml
      - put: demo-app
        params:
          image: image/image.tar