platform: linux
image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task

inputs:
  - name: repository

outputs:
  - name: image

params:
  CONTEXT: repository/demo-app

run: 
  path: build