# permissions for end users to view demoapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demoapp-viewer-role
rules:
- apiGroups:
  - cloudcomputing.rynkbit.com
  resources:
  - demoapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudcomputing.rynkbit.com
  resources:
  - demoapps/status
  verbs:
  - get
