apiVersion: v1
kind: Service
metadata:
  name: concourse-worker
  namespace: concourse
spec:
  selector:
    app: concourse
    type: worker
  type: ClusterIP
  ports:
  - port: 8080
    name: app
  - port: 2222
    name: worker
