apiVersion: v1
kind: Service
metadata:
  name: concourse-web
  namespace: concourse
spec:
  selector:
    app: concourse
    type: web
  type: NodePort
  ports:
  - port: 8080
    name: app
  - port: 2222
    name: worker
