apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: concourse-worker
  namespace: concourse
spec:
  selector:
    matchLabels:
      app: concourse
      type: worker
  serviceName: concourse-worker
  replicas: 3  
  template:    
    metadata:
      labels:
        app: concourse
        type: worker
    spec:      
      containers:
      - name: concourse-worker        
        image: concourse/concourse
        args:
          - worker
        ports:
        - containerPort: 8080
          name: app
        - containerPort: 2222
          name: worker
        - containerPort: 7777
          name: garden
        - containerPort: 7788
          name: baggage-claim
        envFrom:
          - secretRef:
              name: concourse-envvars
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /etc/keys
            name: concourse-keys
          - mountPath: /opt/concourse/worker
            name: concourse-worker
      volumes:
        - name: concourse-keys
          secret:
              secretName: concourse-keys
  volumeClaimTemplates:
  - metadata:
      name: concourse-worker
      namespace: concourse
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
